---
- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- name: disable transparent hugepages through shell
  shell: |-
    echo never | tee /sys/kernel/mm/transparent_hugepage/enabled
    echo never | tee /sys/kernel/mm/transparent_hugepage/defrag
    echo 0 | tee /sys/kernel/mm/transparent_hugepage/khugepaged/defrag
  changed_when: false

- name: disable transparent hugepages in sysfs.d
  block:
  - file: 'path=/etc/sysfs.d state=directory'
  - name: disable transparent hugepages in sysfs
    copy:
      src: 'files/disable_thp.conf'
      dest: "/etc/sysfs.d"
    notify: clean cache
  when: "'sysfsutils' in ansible_facts.packages"

- name: 'RedHat: disable transparent hugepages in grub' 
  command: /usr/sbin/grubby --update-kernel=ALL --args='transparent_hugepage=never'
  when: ansible_os_family == 'RedHat'

- name: "Debian: disable transparent hugepages in grub" 
  copy:
    src: 'files/disable_thp.cfg'
    dest: "/etc/default/grub.d"
  register: update_grub
  when: ansible_os_family == 'Debian'

- name: update grub
  command: update-grub
  when: update_grub.changed
