---
- name: try to detect hugepages size wth postgresql binary (requires PG ver 15+)
  become_user: postgres
  shell: >-
    {{ patroni_postgresql_bin_dir }}/postgres  
    -D {{ patroni_postgresql_conf_dir }}
    --max_connections={{ patroni_bootstrap_dcs_postgresql_parameters | selectattr('option', 'match', 'max_connections') | map(attribute='value') | default(patroni_postgresql_parameters| selectattr('option', 'match', 'max_connections') | map(attribute='value'), true) | default('100', true) | join() }}
    --shared_buffers={{ patroni_bootstrap_dcs_postgresql_parameters | selectattr('option', 'match', 'shared_buffers') | map(attribute='value') | default(patroni_postgresql_parameters| selectattr('option', 'match', 'shared_buffers') | map(attribute='value'), true) | default('128MB', true) | join() }}
    --wal_buffers={{ patroni_bootstrap_dcs_postgresql_parameters | selectattr('option', 'match', 'wal_buffers') | map(attribute='value') | default(patroni_postgresql_parameters| selectattr('option', 'match', 'wal_buffers') | map(attribute='value'), true) | default('16MB', true) | join() }}
    --max_locks_per_transaction={{ patroni_bootstrap_dcs_postgresql_parameters | selectattr('option', 'match', 'max_locks_per_transactions') | map(attribute='value') | default(patroni_postgresql_parameters| selectattr('option', 'match', 'max_locks_per_transactions') | map(attribute='value'), true) | default('64', true) | join() }}
    -C shared_memory_size_in_huge_pages
  register: shared_memory_size_in_huge_pages
  when: patroni_postgresql_version|int >= 15
  
## setup hugepages for PG older than 15
## ((shm size + (BLKSZ - (shm size % BLKSZ))) / (huge page size * 1024)) + 1 = num huge pages

- set_fact: 
    nr_hugepages: "{{ shared_memory_size_in_huge_pages.stdout | default(0) }}"
    hugetlb_shm_group: "{{ (patroni_lock_hugepages_to_group) | ternary(patroni_user.group, '0') }}"

- name: Set hugepages
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_set: true
    reload: true
    sysctl_file: "50-hugepages.conf"
  loop: 
    - { name: 'vm.nr_hugepages', value: nr_hugepages }
    - { name: 'vm.hugetlb_shm_group', value: hugetlb_shm_group }
  register: set_hugepages
  notify: clean cache
    