---
- name: detect if postgresql is running
  postgresql_ping:
  register: pg_ping
  tags: always
  
- import_tasks: postgresql.yml
  when: not pg_ping.is_available and not patroni_postgresql_exists

- import_tasks: user.yml

- import_tasks: disable_thp.yml
  when: patroni_disable_thp

- import_tasks: hugepages.yml
  when: patroni_configure_hugepages
  tags: hugepages
  
- import_tasks: watchdog.yml
  when: patroni_watchdog_mode in ('automatic', 'required')

- name: Install system packages for patroni
  package:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    update_cache: yes
  with_items:
    - "{{ patroni_system_packages }}"
  when: patroni_install_from_pip

- name: Install pip packages for patroni
  pip:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    umask: "{{ item.umask }}"
    executable: "{{ item.executable }}"
  with_items:
    - "{{ patroni_pip_packages }}"
  when: patroni_install_from_pip

