---
- include_tasks: variables.yml
  tags: [always]

- import_tasks: install.yml
  environment:
    DEBIAN_FRONTEND: noninteractive
  tags: [patroni, patroni-install]

- import_tasks: configure.yml
  tags: [patroni, patroni-configure]

- meta: flush_handlers

- name: Ensure patroni is running
  systemd:
    name: patroni.service
    state: started
    daemon_reload: yes
    enabled: yes
  register: patroni_service
  tags: [patroni]

- name: Ensure haproxy is running
  systemd:
    name: haproxy.service
    state: started
    daemon_reload: yes
    enabled: yes
  when: patroni_install_haproxy
