---

- name: Add patroni group
  group:
    name: "{{ patroni_system_group }}"
    state: present
    gid: "{{ patroni_system_group_gid | default(omit)}}"

- name: Add patroni user
  user:
    name: "{{ patroni_system_user }}"
    group: "{{ patroni_system_group }}"
    home: "{{ patroni_system_user_home }}"
    system: yes
    shell: /bin/bash
  register: patroni_user
  tags: always
